apiVersion: apps/v1
kind: Deployment                
metadata:
  name: go-ping          
spec:
  replicas: 3                   
  selector:
    matchLabels:
      app: go-ping       
  template:                     
    metadata:
      labels:                   
        app: go-ping 
    spec:                       
      containers:
      - name: go-ping
        image: rrmanu2001/ping:1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
          
---

apiVersion: v1
kind: Service
metadata: 
  name: go-ping-service
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 9090
    targetPort: 8080
  selector: 
    app: go-ping  